server:
  port: 8088
  servlet:
    encoding:
      force-response: true
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: HTML5
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 2048KB
      max-request-size: 2048KB
  datasource:
    url: jdbc:h2:file:./data/vavishka
    #    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    h2:
      console:
        enabled: true
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
  resources:
    cache: false
    cache.period: 0
  template:
    cache: false
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
app:
  mode:
    debug: true
  service:
    actions:
      session:
        addSession:
          function: addSession
      sample:
        samples:
          function:
          sql:
            type: select
            query: select id, title, description, image_src from samples
            resultType: list
            sequenceName:
        sample:
          sql:
            type: select
            query: select id, title, description, image_src from samples where title=? and description like ?
            resultType: object
            params: 1=title,2=%description%
        sampleById:
          sql:
            type: select
            query: select id, title, description, image_src from samples where id = ?
            resultType: object
            params: 1=id
        addSample:
          sql:
            type: insert
            query: insert into samples (id, title, description, image_src) values(?, ?, ?, ?)
            resultType: object
            sequenceName: vavishka_seq
            params: 1=!,2=title,3=description,4=@1*image.base64&image.rotate&#group
            result: id=!,title=title,description=description,imageSrc=@1
      auth:
        appInfo:
          function: appInfo
static-resource:
  paths:
    '[/**]':
      - classpath:/
      - classpath:/public/
      - classpath:/static/
      - file:///c:/upload-dir/
    '[/bulma]':
      - file:///c:/upload-dir/
storage:
  location: c:/upload-dir
  bean: afterSaveImage
  groups:
    sample:
      folder: sample
      width: 640
      height: 640
    insert-sample-session-image:
      folder: sample-session
      width: 512
      height: 512
      afterSaveImageActivity: insertSampleSessionImageBusiness
    replace-sample-session-image:
      folder: sample-session
      width: 512
      height: 512
      afterSaveImageActivity: replaceSampleSessionImageBusiness
    delete-sample-session-image:
      folder: sample-session
      width: 512
      height: 512
      afterSaveImageActivity: deleteSampleSessionImageBusiness
    session:
      folder: sample-session
      width: 512
      height: 512
      sql: update samples_session set $image_src$ = ? where id = ?
      sqls:
        - delete samples_session_image where samples_session_id = $sampleSessionId$ and orders = $orders$
        - insert into samples_session_image (id, samples_session_id, image_src, orders) values($id$, $sampleSessionId$, $imageSrc$, $orders$)
    header:
      folder: header
      width: 640
      height: 640
      sql: insert into header (path, orders) values (?, ?)
sql:
  groups:
    sample:
      insert: insert into samples (id, title, description, image_src) values(?, ?, ?, ?)
      update: update samples set title = ?, description = ?, image_src = ? where id = ?
      select: select id, title, description, image_src from samples
      delete: delete from samples where id = ?
    session:
      insert: insert into samples_session (id, samples_id, title, description, icon_src, orders) values(?, ?, ?, ?, ?, ?)
      update: update samples_session set title = ?, description = ?, image_src = ? where id = ?
      select: select id, samples_id, title, description, detail, icon_src, orders from samples_session where samples_id = ? order by orders asc
      delete: delete from samples_session where id = ?
  map:
    get-sample-by-id: select id, title, description, image_src from samples where id = ?
    get-session-images: select id, image_src, orders from samples_session_image where samples_session_id = ?
    insert-session-image: insert into samples_session_image (id, image_src, samples_session_id, orders) values (?, ?, ?, ?)
    replace-session-image: update samples_session_image set image_src = ? where id = ?
    delete-session-image: delete samples_session_image where id = ?

